// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Onion.CleanArchitecture.Net.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Onion.CleanArchitecture.Net.WebApp.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240911084255_ChangeColProductTable")]
    partial class ChangeColProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Onion.CleanArchitecture.Net.Domain.Entities.Catalog.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdditionalShippingCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("AdminComment")
                        .HasColumnType("text");

                    b.Property<bool>("AllowAddingOnlyExistingAttributeCombinations")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowBackInStockSubscriptions")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowCustomerReviews")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedQuantities")
                        .HasColumnType("text");

                    b.Property<int>("ApprovedRatingSum")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovedTotalReviews")
                        .HasColumnType("integer");

                    b.Property<bool>("AutomaticallyAddRequiredProducts")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AvailableEndDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AvailableForPreOrder")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AvailableStartDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BackorderMode")
                        .HasColumnType("integer");

                    b.Property<int>("BackorderModeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasepriceAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BasepriceBaseAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("BasepriceBaseUnitId")
                        .HasColumnType("integer");

                    b.Property<bool>("BasepriceEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("BasepriceUnitId")
                        .HasColumnType("integer");

                    b.Property<bool>("CallForPrice")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CustomerEntersPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("DeliveryDateId")
                        .HasColumnType("integer");

                    b.Property<bool>("DisableBuyButton")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisableWishlistButton")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisplayAttributeCombinationImagesOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("DisplayStockAvailability")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisplayStockQuantity")
                        .HasColumnType("boolean");

                    b.Property<int>("DownloadActivationType")
                        .HasColumnType("integer");

                    b.Property<int>("DownloadActivationTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("DownloadExpirationDays")
                        .HasColumnType("integer");

                    b.Property<int>("DownloadId")
                        .HasColumnType("integer");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text");

                    b.Property<int>("GiftCardType")
                        .HasColumnType("integer");

                    b.Property<int>("GiftCardTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Gtin")
                        .HasColumnType("text");

                    b.Property<bool>("HasDiscountsApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSampleDownload")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTierPrices")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUserAgreement")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDownload")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFreeShipping")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGiftCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRental")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShipEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxExempt")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("LimitedToStores")
                        .HasColumnType("boolean");

                    b.Property<int>("LowStockActivity")
                        .HasColumnType("integer");

                    b.Property<int>("LowStockActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("ManageInventoryMethod")
                        .HasColumnType("integer");

                    b.Property<int>("ManageInventoryMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("text");

                    b.Property<bool>("MarkAsNew")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MarkAsNewEndDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MarkAsNewStartDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxNumberOfDownloads")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaximumCustomerEnteredPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("text");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text");

                    b.Property<int>("MinStockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumCustomerEnteredPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NotApprovedRatingSum")
                        .HasColumnType("integer");

                    b.Property<int>("NotApprovedTotalReviews")
                        .HasColumnType("integer");

                    b.Property<bool>("NotReturnable")
                        .HasColumnType("boolean");

                    b.Property<int>("NotifyAdminForQuantityBelow")
                        .HasColumnType("integer");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("OrderMaximumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("OrderMinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OverriddenGiftCardAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ParentGroupedProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PreOrderAvailabilityStartDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProductAvailabilityRangeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProductCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProductTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("RecurringCycleLength")
                        .HasColumnType("integer");

                    b.Property<int>("RecurringCyclePeriod")
                        .HasColumnType("integer");

                    b.Property<int>("RecurringCyclePeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("RecurringTotalCycles")
                        .HasColumnType("integer");

                    b.Property<int>("RentalPriceLength")
                        .HasColumnType("integer");

                    b.Property<int>("RentalPricePeriod")
                        .HasColumnType("integer");

                    b.Property<int>("RentalPricePeriodId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireOtherProducts")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredProductIds")
                        .HasColumnType("text");

                    b.Property<int>("SampleDownloadId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShipSeparately")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<bool>("ShowOnHomepage")
                        .HasColumnType("boolean");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("SubjectToAcl")
                        .HasColumnType("boolean");

                    b.Property<int>("TaxCategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("UnlimitedDownloads")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseMultipleWarehouses")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgreementText")
                        .HasColumnType("text");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.Property<bool>("VisibleIndividually")
                        .HasColumnType("boolean");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("Products", "public");
                });

            modelBuilder.Entity("Onion.CleanArchitecture.Net.Domain.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", "public", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
